name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability. 
version: 3.1.0
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^1.4.2
  json_annotation: ^3.0.0
  clock: ^1.0.1
  # speech_to_text_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  fake_async: ^1.0.1
  mockito: ^4.1.1
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
      # web:
      #   pluginClass: SpeechToTextPlugin
      #   fileName: speech_to_text_web.dart
